scottish-government-design-system/design-system

- .npmignore
- CODE_OF_CONDUCT.md
- add CODE_OF_CONDUCT.md
- add CODE_OF_CONDUCT.md and the .github folder to .npmignore
> DS-423 add code of conduct

- .github/ISSUE_TEMPLATE/bug_report.md
Adds a "bug report" issue template
> DS-422 Update issue templates

- .github/workflows/release-package.yml
- src/all.js
- src/base/tools/tracking/tracking.js
- src/version.js
- adds version number to data layer if statistics cookies are permitted
- adds version number to window.DS object
- updates version number in package-lock.json
> DS-414 Include current version number in data layer

- babel.config.js
- src/base/helpers/_all.scss
- src/base/helpers/functions/_functions.scss
- src/base/helpers/layout/_layout.scss
- src/base/tools/tracking/tracking.js
- src/components/accordion/_accordion.scss
- src/components/accordion/accordion.js
- src/components/accordion/accordion.test.js
- src/components/back-to-top/_back-to-top.scss
- src/components/back-to-top/back-to-top.js
- src/components/back-to-top/back-to-top.test.js
- src/components/date-picker/_date-picker.scss
- src/components/date-picker/date-picker.js
- src/components/details/_details.scss
- src/components/details/details.js
- src/components/side-navigation/_side-navigation.scss
- src/components/side-navigation/side-navigation.js
- src/components/side-navigation/side-navigation.test.js
- src/components/site-navigation/_site-navigation.scss
- src/components/site-navigation/site-navigation.js
- src/components/step-navigation/_step-navigation.scss
- webpack.config.js
use CSS custom properties in preference to inline styles
use sass:math for division
> Breaking changes

- CHANGELOG.md
- src/components/back-to-top/_back-to-top.scss
- src/components/back-to-top/back-to-top.js
Resolve conflict in _back-to-top.scss
DS-466 Back to top position incorrect
Changelog for 1.0.0
> Final changes ahead of major release

- src/components/side-navigation/side-navigation.js
- src/components/side-navigation/side-navigation.test.js
- src/forms/character-count/character-count.js
- src/forms/character-count/character-count.test.js
This causes multiple open/close buttons to be created
This fix has also been applied to character count
> DS-459 Side navigation: component can be initialised multiple times

- src/components/autocomplete/_autocomplete.scss
- src/components/side-navigation/_side-navigation.scss
- src/components/site-search/_site-search.scss
DS-398 Autocomplete suggestions (and site search) border colour contrast
DS-399 Side menu mobile toggle button colour contrast
> DS-398, DS-399 colour contrast updates for autocomplete and side nav

- src/base/core/_all.scss
- src/base/core/mark/_mark.scss
- src/base/helpers/high-contrast/_high-contrast.scss
- src/base/helpers/links/_links.scss
- src/base/helpers/media-query/_media-query.scss
- src/components/autocomplete/_autocomplete.scss
- src/components/autocomplete/highlight.js
- src/components/details/_details.scss
- src/components/search-result/_search-result.scss
- src/components/task-list/_task-list.scss
Also:
DS-567 Reduce duplication: bring "mark" into base/core
DS-568 Reduce duplication: create a mixin for the high contrast media query
> DS-522 Search result parent link flagpole has incorrect height on mobile

- src/base/objects/layout/_layout.scss
- addition of "navigation" to default layout
- update to search results with filters layout
> DS-576 Layout improvements

- src/components/accordion/_accordion.scss
- src/components/side-navigation/_side-navigation.scss
Adjust chevron size and placement to match accordion component
> DSP-613 Fix line height on side navigation

- src/components/site-branding/_site-branding.scss
- src/components/site-footer/_site-footer.scss
- src/components/site-navigation/_site-navigation.scss
- src/components/tag/_tag.scss
- remove ds_reversed additions from "site branding"
- remove ds_reversed additions from "site footer"
- remove ds_reversed additions from "site navigation"
- remove ds_reversed additions from "tag"
> DSP-658 Remove "reversed" site header and site footer variants

- src/components/sequential-navigation/_sequential-navigation.scss
> DSP-760 Sequential nav: change colour of "previous" and "next" text to main text colour

- src/components/autocomplete/autocomplete.js
- status readout of current number of items (e.g. “there are 6 options“) gets announced when the field is refocused
- status readout for current number of items gets read out when the content of the text field has changed but the number of suggestions remains the same
- status readout for selected item (e.g. "1 of x") is read out only once
> DSP-757 Autocomplete: status readout improvements for screen readers

- src/components/inset-text/_inset-text.scss
- also add spacing rule for tags inside inset text
> DSP-675 tighter padding on inset text

- src/components/details/_details.scss
- src/components/notification-banner/_notification-banner.scss
- src/components/notification-banner/notification-banner.js
- src/components/notification-panel/_notification-panel.scss
- src/components/notification-panel/readme.md
- src/components/task-list/_task-list.scss
- src/forms/text-input/_text-input.scss
- details to get ds_last-child-no-margin
- notification to use js-initialised to control display of its close button
- notification panel to use green colourway by default
- task list to get space between task text and task status
- input wrapper to only add space for a button when it contains a button
> DSP-858 Miscellaneous defects found while doing the React work

- src/base/tools/tracking/tracking.html
- src/base/tools/tracking/tracking.js
- src/base/tools/tracking/tracking.test.js
- src/forms/character-count/character-count.js
- src/forms/character-count/character-count.test.js
character count fixes for inconsistent use of full stops and a failing unit test 
tracking attributes updated for summary list and summary card with updated unit tests for tracking
> dsp-864 Updates to tracking script and character count

- src/components/phase-banner/_phase-banner.scss
- src/components/tag/_tag.scss
- new colourways
- add outline
- lowercase/capitalised and normal-weight text
- no rounded corners
> dsp-655 enhancements to tag component

- src/components/task-list/_task-list.scss
> dsp-882 mark task list status tag as deprecated

- src/components/warning-text/_warning-text.scss
Uses CSS filter so needs IE11 fallback
> DSP-931 Change warning text icon to SVG background

- src/base/helpers/links/_links.scss
- src/base/objects/page/_page.scss
- src/base/settings/colours/_colours.scss
- src/components/card/_card.scss
- src/components/side-navigation/_side-navigation.scss
- src/components/site-navigation/_site-navigation.scss
- src/components/site-search/_site-search.scss
- src/components/summary-list/_summary-list.scss
- src/components/table/_table.scss
- src/components/tabs/_tabs.scss
- src/images/icons/svg/checkbox.svg
- src/images/icons/svg/radio.svg
Combining two tickets to save on conflicts
> Colour changes

- src/base/helpers/links/_links.scss
- src/components/accordion/_accordion.scss
- src/components/accordion/accordion.js
- src/components/search-results/_search-filters.scss
- src/components/step-navigation/_step-navigation.scss
- include visible text on the open/close indicator
- move open/close indicator under the accordion title
- add variables for DS link underline display so the open/close indicator's display can be kept in sync with link styling more easily
- spacing tweaks for accordion and components that include accordions (step navigation, search filters)
> DSP-1013 Accordion accessibility updates

- src/base/core/links/_links.scss
- src/base/helpers/_all.scss
- src/base/helpers/fancy-underscore/_fancy-underscore.scss
- src/base/helpers/high-contrast/_high-contrast.scss
- src/base/helpers/links/_links.scss
- src/base/helpers/media-query/_media-query.scss
- src/base/helpers/scrollbar/_scrollbar.scss
- src/components/accordion/_accordion.scss
- src/components/autocomplete/_autocomplete.scss
- src/components/button/_button.scss
- src/components/card/_card.scss
- src/components/confirmation-message/_confirmation-message.scss
- src/components/date-picker/_date-picker.scss
- src/components/details/_details.scss
- src/components/link-item/_link-item.scss
- src/components/notification-banner/_notification-banner.scss
- src/components/pagination/_pagination.scss
- src/components/search-results/_search-facets.scss
- src/components/search-results/_search-filters.scss
- src/components/search-results/_search-result.scss
- src/components/sequential-navigation/_sequential-navigation.scss
- src/components/site-branding/_site-branding.scss
- src/components/site-navigation/_site-navigation.scss
- src/components/step-navigation/_step-navigation.scss
- src/forms/_form.mixins.scss
- src/forms/error-summary/_error-summary.scss
- src/forms/select/_select.scss
- link hover underline offset and width now a relative value
- various components updated to use those new values where they aren't automatically picking them up
- link hover dark bottom line now a relative value
> DSP-970 Update to link hover styling

- src/components/card/_card.scss
- src/components/search-results/_search-result.scss
- src/components/site-branding/_site-branding.scss
Fix to site branding to show left outline when in focus 
Fix to search result image links to get blocklink styling applied correctly 
Fix to size and spacing of image within small image variant of a card
> DSP-1181 Various link fixes

- src/base/settings/colours/_colours.scss
Internal Jira link for simplicity: https://sg-dtd.atlassian.net/browse/DSP-1262
> DSP-1262 Update dark green/positive state messaging colour

- src/base/helpers/colours/_colours.scss
- src/components/feature-header/_feature-header.scss
Links use foreground colour on hover when feature header has a background colour applied
> DSP-1285 Feature header link hover colour fix

- src/base/tools/tracking/tracking.html
- src/base/tools/tracking/tracking.js
- src/base/tools/tracking/tracking.test.js
- src/components/hide-this-page/hide-this-page.test.js
> DSP-1093 Tracking script updates

- src/components/date-picker/_date-picker.scss
- src/forms/_form.base.scss
- src/forms/hint-text/_hint-text.scss
- src/forms/label/_label.scss
- src/forms/question/_question.scss
- new margins for hint text
- include font size/leading on .ds_label class so it can be used to modify legend elements appropriately
> DSP-1061 Form spacing and legend sizing changes

- src/components/back-to-top/back-to-top.js
- use ResizeObserver instead of listening for window resize
> DSP-1339 Back to top: component gets confused by async page updates

- src/base/tools/tracking/tracking.js
Fix by not using aria-describedby to find the question associated with the action button
> DSP-1357 Tracking script error: referencing multiple items in aria-describedby triggers error
